{% set name = "hvpy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hvpy-{{ version }}.tar.gz
  sha256: e645fe489aad94b557d41d2ab93a433f105debd3b8c6e2fe87bd2b70df0a9e2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydantic-settings >=2.0.0
    - pydantic >=2.0.0
    - requests

test:
  imports:
    - hvpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hvpy.readthedocs.io/en/latest/
  summary: Helioviewer Python API Wrapper
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://hvpy.readthedocs.io/en/latest/
  dev_url: https://github.com/Helioviewer-Project/python-api

extra:
  recipe-maintainers:
    - dgarciabriseno
    - wafels
    - nabobalis
